### ISSUE TITLE
Intermittent "No result for source categories"

### ISSUE THREAD

**Issue by matkoniecz** [magnusmanske/petscan_rs#106]
According to https://commons.wikimedia.org/w/index.php?title=Commons:Village_pump&oldid=594602179#What_is_wrong_with_PetScan? PetScan is known to be working only sometimes ("Petscan is infamously unstable for silently refusing to return anything."), but it seemed to not be reported here 

Even if it is deployment issue that it gets insufficient resources less confusing errors ("Server overloaded, unable to return results") would be preferable.

I get an intermittent

![screen01](https://user-images.githubusercontent.com/899988/135437864-de1a6fbc-57e2-4626-a69d-fad9cac38afb.png)

on queries where this is not an actual problem. See for example https://petscan.wmflabs.org/?since_rev0=&language=commons&edits%5Bflagged%5D=both&search_max_results=500&cb_labels_no_l=1&edits%5Bbots%5D=both&%C2%AEexp_filter=&ns%5B6%5D=1&langs_labels_no=%C2%AEexp_filter&cb_labels_yes_l=1&cb_labels_any_l=1&edits%5Banons%5D=both&project=wikimedia&interface_language=en&negcats=Diagrams%20of%20road%20signs%0AMonochrome%20photographs&categories=Speed%20bumps%0A&depth=100& that (unless I bungled something recently returned images) then on rerun put this confusing message

**Comment by dpriskorn** [comment]
I also recently tried searching based on a category and got no results.

**Comment by matkoniecz** [comment]
Monochrome photographs seems the main problem. I know that "except huge category" is annoying/impossible to implement, but in such case it would be nicer to return a less misleading error.

https://petscan.wmflabs.org/?links_to_all=&depth=100&categories=Speed%20bumps%0A&manual_list=%C2%AEexp_filter=&project=wikimedia&edits%5Bbots%5D=both&since_rev0=&cb_labels_yes_l=1&language=commons&negcats=Monochrome%20photographs&cb_labels_any_l=1&ns%5B6%5D=1&search_max_results=500&edits%5Banons%5D=both&edits%5Bflagged%5D=both&langs_labels_no=%C2%AEexp_filter=&cb_labels_no_l=1&interface_language=en

**Comment by dme212** [comment]
I just ran a query for **one category** [American academics](https://en.wikipedia.org/wiki/Category:American_academics).

I am getting zero hits--nothing for Depth=0, Depth=1. I think Petscan began chocking when I changed Depth from 0.

[https://petscan.wmflabs.org/?psid=20290800](https://petscan.wmflabs.org/?psid=20290800)

**Comment by aymatth2** [comment]
I am getting "Category/templates search was run but returned no results. You might want to check the parameters" intermittently for the same canned query. Sometimes it works, sometimes not. Maybe there is a server somewhere that times out, or something?

**Comment by enfascination** [comment]
I'm encountering this issue as well.  It seems related to load: I can reproduce it reliably when (simulating my students all working right before deadline) I run the same large, slow, high-depth query at the same time from multiple notebooks (on the same IP).

I couldn't reproduce the issue directly on the petscan.wmflabs.org interface (even with four copies of this 5-15 minute query running at the same time:
https://petscan.wmflabs.org/?psid=22075099 )

but I can consistently reproduce it running four copies of the same query on four different Python notebooks coming from the same IP:
```
import requests
parameters = {'language' : 'en',
              'project' : 'wikipedia',
              'depth' : 10,
              'categories' : "People from New York City",
              'combination' : "union",
              'format' : 'json',
              'doit' : 1}

r = requests.get('https://petscan.wmflabs.org/', params=parameters)
r.json()
```

**Comment by Wolfdietmann** [comment]
I'm encountering this issue as well. It doesn´t seem related to load. PETSCAN doesn´t even remember the PSID. Instead it seems to be related to "Templates&Links": "Links from" and "Links to" render normal results, "Templates" does not. Is anybody working on this longlasting annoyance?

**Comment by MugaSofer** [comment]
Just ran into this issue as well, searching directly from the petscan.wmflabs.org interface. I scanned a category (Technology_by_type), it worked but that category is composed entirely of sub-categories, so I increased the depth (to 10, which was perhaps too high and overloaded something?) "No result for source categories". 

I tried changing the depth back to 0, even tried making the same search in a different tab, but just got "No result for source categories" each time. 

After a few minutes, it fixed itself.

It's pretty reasonable for an error to be thrown if you try to load truly absurd numbers of pages, but the error it currently throws is definitely misleading.

**Comment by dpriskorn** [comment]
This sounds like very unclear error messages.
Has anyone looked at the source?
Maybe inserting better error logging could help locate the cause?

Since Magnus is unlikely to do this I suggest you fork petscan and set up a development instance in toolforge or wherever possible

**Comment by magnusmanske** [comment]
Debugging output revealed that max_user_connections is exhausted because of too many (sub)queries. If you lower https://petscan.wmflabs.org/?since_rev0=&language=commons&edits%5Bflagged%5D=both&search_max_results=500&cb_labels_no_l=1&edits%5Bbots%5D=both&%C2%AEexp_filter=&ns%5B6%5D=1&langs_labels_no=%C2%AEexp_filter&cb_labels_yes_l=1&cb_labels_any_l=1&edits%5Banons%5D=both&project=wikimedia&interface_language=en&negcats=Diagrams%20of%20road%20signs%0AMonochrome%20photographs&categories=Speed%20bumps%0A&depth=100&  from 100 to 10 it works just fine. I will try to limit the number of queries.
