### ISSUE TITLE
Link to a pre-filled form for the query you just ran *without* - linefeed fail 

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/petscan_rs#11]
Petscan with a couple of negative categories - http://petscan.wmflabs.org/?psid=10743146 - becomes a Petscan with a single concatenated (and thus non functional) negative category when the "without" link is followed - http://petscan.wmflabs.org/?wikidata_source_sites=&interface_language=en&negcats=Articles%20for%20deletionAll%20articles%20proposed%20for%20deletion&ns%5B0%5D=1&wikidata_item=without&project=wikipedia&sortby=title&edits%5Bflagged%5D=both&language=en&categories=living%20people&edits%5Banons%5D=both&edits%5Bbots%5D=both&show_redirects=no&search_max_results=500&min_sitelink_count=

Same error found on the Categories - they, too, concatenate after traversing a 'without' link.

<img width="503" alt="Screenshot 2019-08-25 at 17 08 34" src="https://user-images.githubusercontent.com/9000789/63652690-00bf5000-c75b-11e9-9300-057e5a5c58c2.png">
<img width="397" alt="Screenshot 2019-08-25 at 17 08 25" src="https://user-images.githubusercontent.com/9000789/63652691-0157e680-c75b-11e9-8c41-57c57c798403.png">

**Comment by magnusmanske** [comment]
This should be fixed now.
