### ISSUE TITLE
 Prepared statement contains too many placeholders 

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/petscan_rs#12]
Query below works at depth=3, but at depth=5 gives:

datasource_database::go_depth: MySqlError { ERROR 1390 (HY000): Prepared statement contains too many placeholders }

http://petscan.wmflabs.org/?language=en&project=wikipedia&depth=5&categories=people%20by%20occupation&negcats=Articles%20for%20deletion&ns%5B0%5D=1&show_redirects=no&search_max_results=500&wikidata_item=with&wikidata_prop_item_use=P31%2CP279&wpiu=none&sortby=title&interface_language=en&active_tab=

**Comment by magnusmanske** [comment]
I believe I fixed the bug, however, the query becomes so large I don't know how long it will take to finish. [Depth 4, all pages (not redlinks)](http://petscan.wmflabs.org/?psid=10858638) gives 17681 pages in 6 minutes, but (a) depth 5 is many times more pages to check, (b) redlinks is slow on top.

**Comment by magnusmanske** [comment]
_Update_ I got it running on my local machine, ~30min. Needs to check over 2 million pages from 250,000 categories. Databases are fast but not that fast.

**Comment by magnusmanske** [comment]
I am closing this issue, as the "too many placeholders" issue is solved.

The query, as it is, likely won't run through, but that's just because you ask a great deal of the database.
