### ISSUE TITLE
 Eerror? "®exp_filter"

### ISSUE THREAD

**Issue by JotaCartas** [magnusmanske/petscan_rs#120]
Sometimes when you get no results it shows  the error? "®exp_filter" in (any/different) tabs and we have to clean them before the "PetSacan" works again
![Screenshot 2022-05-25 174140](https://user-images.githubusercontent.com/59584609/170894936-df08c3b7-b04a-4c98-bb3e-39101c048f33.jpg)
![Screenshot 2022-05-26 200819](https://user-images.githubusercontent.com/59584609/170894796-35636b62-8944-4b4c-bf50-bac775dc804a.jpg)

**Comment by sdkb** [comment]
This happens all the time, and makes PetScan significantly less usable. Any idea what's causing it or how to resolve?

**Comment by jonesey95** [comment]
I am seeing this too, along with various error messages, even when I clear this problem, telling me that Petscan is unable to retrieve articles that match my query, even though I know that they exist. I am a pretty experienced Petscan user. This should be higher-priority.

**Comment by JotaCartas** [comment]
Today, a different error  "®exp_filter"

![Screenshot 2023-03-21 062417](https://user-images.githubusercontent.com/59584609/226532409-5f388d83-3a5a-4adc-a97b-fe1e5d530b3f.jpg)

**Comment by magnusmanske** [comment]
I have replaced 'regexp_filter' with 'rxp_filter', which should prevent the issue. 'regexp_filter' is still supported for backwards compatibility.
