### ISSUE TITLE
Petscan not finding template

### ISSUE THREAD

**Issue by robertsilen** [magnusmanske/petscan_rs#121]
I created the template [Mall:SLS Q](https://sv.wikipedia.org/wiki/Mall:SLS_Q) in Swedish Wikipedia, and a corresponding one in [English](https://en.wikipedia.org/wiki/Template:SLS_Q). Petscan finds articles using the template on the [English Wikipedia (see Petscan query)](https://petscan.wmflabs.org/?psid=22672227), but not on [Swedish (see Petscan query)](https://petscan.wmflabs.org/?psid=22672206). What is going on here, is it a bug, or how can I fix it? Thank for help.

**Comment by whpac** [comment]
It appears to be related to migration of some fields from `templatelinks` to `linktarget` table in the MediaWiki database.

**Comment by robertsilen** [comment]
Sounds great, thank you! Is this fix already online? I'm still running into the same error with the query mentioned.

**Comment by whpac** [comment]
> Sounds great, thank you! Is this fix already online? I'm still running into the same error with the query mentioned.

It's not online yet. The pull request has to be accepted by someone who has write access to this repository.

**Comment by robertsilen** [comment]
@magnusmanske @simon04 @1-Byte - there is a fix waiting to be accepted. This is a friendly ping wondering how the process works for getting this online? :)

**Comment by robertsilen** [comment]
@magnusmanske Thank you!
