### ISSUE TITLE
PSID link and prefilled query link is not visible

### ISSUE THREAD

**Issue by zache-fi** [magnusmanske/petscan_rs#123]
After user executes the query there used to be PSID with link to it AND link with prefilled parameters. Currently they are not visible any more. (PSID number seems to be hidden by CSS, but I am not sure if there is prefilled link)

**Comment by DP-jawiki** [comment]
Under my environment, I also have a problem with PSID number not generated. Any fixes?

**Comment by wargo32** [comment]
This is the cause: https://github.com/magnusmanske/petscan_rs/blob/d192a92947678b27a466b21df2d5a6dca3b2d332/html/main.js#L84
