### ISSUE TITLE
Retrieve article text

### ISSUE THREAD

**Issue by sreza1** [magnusmanske/petscan_rs#126]
Hi,

I've been using https://petscan.wmflabs.org/ and its super useful retrieving article id. However I'm trying to see if its possible to return the article text itself. Wondering if it's possible or are there any plans for this feature to be made?

**Comment by magnusmanske** [comment]
PetScan, or Toolforge in general, has no "privileged" way to get to article text. So it would have to query the respective API and add the text to the returned data, which would increase runtime and transfered data. Meanwhile, the client can just request the text on their own. I don't see a good reason to implement this.
