### ISSUE TITLE
Path from a category to a page/article

### ISSUE THREAD

**Issue by SalamAazam** [magnusmanske/petscan_rs#129]
I am not sure where to post this. What I wanted to know is how may I know how a page is related to a specific category. e.g. a Wikipedia page (x) that is in the depth three of y: How y is linked to x? That is, what are the first category, second category, third category, and article page? As in Category One name -> Category Two name -> Category Three name -> Wikipedia article name.

Many thanks.

Kind regards,
Salam

**Comment by magnusmanske** [comment]
This information is not readily available in PetScan. First, a list of all subcategories in a tree is constructed, then pages in any of these subcategories are found. The information about specific paths is not captured.
