### ISSUE TITLE
Last edit filtering ignored and last change date incorrect

### ISSUE THREAD

**Issue by lokal-profil** [magnusmanske/petscan_rs#13]
I tried running our semi-annual scan for new images uploaded through support of our chapter and spotted that old and new petscan give vastly different results. The scan looks for files on Commons in a few categories created between two timestamps. [New petscan with 22258 hits](https://petscan.wmflabs.org/?psid=10805968) / [Old petscan with 1670 hits](https://petscan1.wmflabs.org/?psid=10805968). I'm re-using the same psid so I know this is not due to an input difference.

It looks as though new petscan has two issues:

Firstly I get the same number of hits when I run [the scan without the timestamp filtering](https://petscan.wmflabs.org/?psid=10806274).

Secondly looking at [the first hit](https://commons.wikimedia.org/wiki/File:Norrb%C3%A4rke_kyrka_by_night.jpg) it says last_change = 20190117032154 but neither the revision history nor the log shows any changes since 2017.

**Comment by magnusmanske** [comment]
This is fixed now.

**Comment by lokal-profil** [comment]
Thanks!
