### ISSUE TITLE
Petscan returns lower number of articles if search by two categories than Wikipedia

### ISSUE THREAD

**Issue by maximmasiutin** [magnusmanske/petscan_rs#143]
Do you know why Petscan gives a shorter list than Wikipedia if I search for articles having two categories (Intersection)?

For example, if I get the list of articles having the following categories:
* Autosomal recessive disorders
* Good articles

, Wikipedia returns 6 articles whereas Petscan returns only 4.

**Comment by magnusmanske** [comment]
How do you get the intersection from Wikipedia? Search only gives me the same four:
https://en.wikipedia.org/w/index.php?search=incategory%3A%22Autosomal+recessive+disorders%22+incategory%3A%22Good+articles%22&title=Special:Search&profile=advanced&fulltext=1&ns0=1

If you increase the depth for "Autosomal recessive disorders" you can actually get 7 pages from PetScan:
https://petscan.wmflabs.org/?psid=26806520

**Comment by maximmasiutin** [comment]
Sorry, I wanted to get back to this issue and provide you with the most complete information, but when I go to https://petscan.wmflabs.org/?psid=26806520 (or to just https://petscan.wmflabs.org/ ) I get an error, and this already last about one day so far, the error is the following:
```
Wikimedia Cloud Services Error

This web service cannot be reached. Please contact a maintainer of this project.
```

**Comment by magnusmanske** [comment]
Someone rebooted the server but petscan didn't restart. Fixed now.

**Comment by maximmasiutin** [comment]
> If you increase the depth for "Autosomal recessive disorders" you can actually get 7 pages from PetScan:
> https://petscan.wmflabs.org/?psid=26806520

Yes, thank you, you are right! Petscan works correctly, please consider this issue closed.
