### ISSUE TITLE
Wrapper (or sample) to run queries from the command line without an http server

### ISSUE THREAD

**Issue by maximmasiutin** [magnusmanske/petscan_rs#146]
Could you please consider adding a wrapper (or a sample) to run queries from the command line without an http server.

For example, I run
`./petscan.sh --query="language=en&project=wikipedia&categories=Cytochrome+P450&negcats=Enzymes&regexp_filter=CYP.*"`
and receive the results to stdout?

**Comment by magnusmanske** [comment]
You can now run the binary with a parameter containing the URL query part. It will default to JSON output unless you specify another, non-HTML one.
