### ISSUE TITLE
[feature request] Allow structured data editing for Wikimedia Commons files

### ISSUE THREAD

**Issue by fokky** [magnusmanske/petscan_rs#15]
PetScan makes it possible to add or remove Wikidata statements to Wikidata items - a handy feature that I use a lot.

![image](https://user-images.githubusercontent.com/9881645/64016304-e6082500-cb26-11e9-9b14-f54745a89069.png)

Would it be a good idea, and feasible, to add a similar feature, that allows to add/remove [structured data statements]([url](https://commons.wikimedia.org/wiki/Commons:Structured_data)) to lists of files from Wikimedia Commons?

**Comment by magnusmanske** [comment]
I doubt I'll implement it for PetScan, but it will come (and partially works) in QuickStatements, which you can open from PetScan. I'll leave this issue open until that is in place, then close it.

**Comment by magnusmanske** [comment]
This is done now.
