### ISSUE TITLE
PetScan is down

### ISSUE THREAD

**Issue by fee1-dead** [magnusmanske/petscan_rs#155]
Looks like PetScan is currently down.

**Comment by A-smart-kitten** [comment]
Visiting https://petscan.wmflabs.org/ displays the error "This web service cannot be reached. Please contact a maintainer of this project."
<img width="836" alt="image" src="https://github.com/magnusmanske/petscan_rs/assets/156261517/93bcb5d6-2c63-4d6a-be54-c5f459cd0ddd">

**Comment by A-smart-kitten** [comment]
Currently running again, it looks like :)
