### ISSUE TITLE
Petscan/Glamorgan CORS error

### ISSUE THREAD

**Issue by Ambrosiani** [magnusmanske/petscan_rs#16]
hi, I get the following error when trying to run Glamorgan. Is this related to the new Petscan version?

> Access to XMLHttpRequest at 'https://petscan.wmflabs.org/?lang=commons&project=wikimedia&cats=Images+from+Nordiska+museet&ns=6&depth=12&max=30000&start=0&format=json&giu=1&redirects=0' from origin 'https://tools.wmflabs.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by magnusmanske** [comment]
I patched Glamorgan to use JSONP instead, should work fine now.

**Comment by Ambrosiani** [comment]
as always, a huge thank you @magnusmanske for keeping these tools running!
