### ISSUE TITLE
Shows 0 results when there should be many results (dysfunctional most of the time)

### ISSUE THREAD

**Issue by prototyperspective** [magnusmanske/petscan_rs#161]
I don't think it's a duplicate of #148

This refers to searches of category intersections of media files on Wikimedia Commons (click on Commons in the upper right then enter categories and negative categories and change the depth).

Currently, petscan is mostly useless to me since most of the time it just returns a yellow message box with:

**0 results**
> Category/templates search was run but returned no results. You might want to check the parameters

Sometimes, it does work but I haven't figured out yet what is causing it to not return any results some times. That for the exact same search, it sometimes shows the 0 results and sometimes shows many results.

In the Firefox console nothing is shown when pressing search but three messages "Some cookies are misusing the recommended “SameSite“ attribute". Petscan is an extremely useful and critical tool for populating categories and I hoped this issue would be solved but it has persisted for many months now.

**Comment by magnusmanske** [comment]
Example query/PSID?

**Comment by prototyperspective** [comment]
It's working again. The strange thing is that the same query sometimes did work but most of the time didn't. Will close and create a separate issue for the related remaining issue.
