### ISSUE TITLE
no result frwiki category + use none items/props cross-section

### ISSUE THREAD

**Issue by SimonVilleneuvewp** [magnusmanske/petscan_rs#164]
Hi,

The query #28077834 give more than 8000 results, but the #28077844 give no result. There should be at least https://www.wikidata.org/wiki/Q76147584 , who is in the first but not in the second query.
Is it bad doctor ?

**Comment by M2k-dewiki** [comment]
Hello, please also see
* https://phabricator.wikimedia.org/T363073
* https://de.wikipedia.org/w/index.php?title=Benutzer_Diskussion%3AM2k%7Edewiki&diff=244261852&oldid=244251670
Thanks a lot!

**Comment by M2k-dewiki** [comment]
Maybe this is releated to the last commit?
    https://github.com/magnusmanske/petscan_rs/commit/8c8cc1ca490fdd969e86d8ef9d92f16bfb5fc9f8

-----------

The affected HTML form parameter is 
        wikidata_prop_item_use

**Comment by belegdal** [comment]
Query #27401267 is also affected by this issue; most of the returned results do not include the items/props required by the query.

**Comment by hgzh** [comment]
I've added comments to the lines in 8c8cc1c that should cause some malfunctions.

**Comment by M2k-dewiki** [comment]
Also see
* https://de.wikipedia.org/wiki/Wikipedia:Technische_W%C3%BCnsche/Reparaturhilfe#PetScan:_Suche_nach_Wikidata-Objekten_ohne_eine_bestimmte_Eigenschaft
* https://de.wikipedia.org/w/index.php?title=Wikipedia%3ATechnische_W%C3%BCnsche%2FReparaturhilfe&diff=244967036&oldid=244161075

**Comment by magnusmanske** [comment]
Applied fixes, please close this issue if it's fixed now!

**Comment by SimonVilleneuvewp** [comment]
it's better. I now have 2 results instead of 0 for #28077844 , but Q76147584 isn't in.

**Comment by M2k-dewiki** [comment]
Vielen Dank funktioniert bei mir allerdings leider noch nicht. Beispielsweise sollte
https://petscan.wmflabs.org/?psid=28297821
eine Liste von verstorbenen Personen ohne Sterbedatum im Wikidata-Objekt liefern, normalerweise sind das ein paar tausend Einträge. Weitere Beispiele sind unter
https://www.wikidata.org/wiki/User:M2k~dewiki/Tools/Enrich_Objects#Beruf_/_Tätigkeit
zu finden.

**Comment by M2k-dewiki** [comment]
Hello, today it worked for me again! 

Thanks a lot!

**Comment by SimonVilleneuvewp** [comment]
seems good for me too

**Comment by SimonVilleneuvewp** [comment]
thank you
