### ISSUE TITLE
Breaking change: Flagged pages is broken

### ISSUE THREAD

**Issue by lorinczz** [magnusmanske/petscan_rs#169]
Example and reason on the following link:
https://phabricator.wikimedia.org/T367966

**Comment by NovemLinguae** [comment]
Copying of the above post:

> [PetScan query](https://petscan.wmflabs.org/?templates_any=&rxp_filter=%C2%AEexp_filter&show_redirects=both&output_compatability=catscan&since_rev0=&labels_any=&langs_labels_yes=&search_max_results=500&sparql=&depth=10&ns%5B0%5D=1&interface_language=en&wikidata_item=no&edits%5Bflagged%5D=no&namespace_conversion=keep&search_wiki=&project=wikipedia&language=hu&sitelinks_yes=&categories=Rom%C3%A1nia&page_image=any&langs_labels_any=&cb_labels_any_l=1&wikidata_label_language=&sitelinks_no=&links_to_any=&common_wiki_other=&sortby=date&outlinks_yes=&cb_labels_yes_l=1&referrer_url=&cb_labels_no_l=1&sortorder=descending&maxlinks=&ores_prediction=any&manual_list_wiki=&show_disambiguation_pages=both&langs_labels_no=&larger=&pagepile=&active_tab=tab_categories&format=html&negcats=Labdar%C3%BAg%C3%B3k%0D%0ALabdar%C3%BAg%C3%B3csapatok%0D%0ATelev%C3%ADzi%C3%B3csatorn%C3%A1k%0D%0ATelev%C3%ADzi%C3%B3t%C3%A1rsas%C3%A1gok%0D%0ARom%C3%A1nia+%C3%A9l%C5%91vil%C3%A1ga) fails with the following error:
>
> Server(ServerError { code: 1356, message: "View 'huwiki_p.flaggedpage_pending' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them", state: "HY000" })

**Comment by NovemLinguae** [comment]
A search of the codebase for flaggedpage_pending reveals this. This is probably the code that needs updating:

https://github.com/magnusmanske/petscan_rs/blob/3c3f3cc7ae76f441bdcc0604fe30f64c7bbac4c1/src/datasource_database.rs#L1083-L1091

**Comment by zache-fi** [comment]
Afaik, this would work with same logic than SQL query with flaggedpage_pending.

"yes" => sql.0 += 
         " AND NOT EXISTS (SELECT * FROM flaggedpages WHERE fp_pending_since IS NOT NULL AND fp_page_id=p.page_id )", 
     "no" => { 
         sql.0 += 
             " AND EXISTS (SELECT * FROM flaggedpages WHERE fp_pending_since IS NOT NULL AND fp_page_id=p.page_id )" 
     }

**Comment by lorinczz** [comment]
Description of the change:

Get rid of flaggedpage_pending table

This table was useful when we had several quality tiers but not anymore.

As it's written in documentation of the table:
> Basically the same as flaggedpages, without the rows where fp_pending_since
> is NULL. Was more useful in the past when there were multiple quality tiers.

Refactor the one place it actually makes the query (for updating stats)
and Special:PendingChanges if you provide levels (which we don't)
