### ISSUE TITLE
The tool is completely broken

### ISSUE THREAD

**Issue by danielyepezgarces** [magnusmanske/petscan_rs#184]
Petscan is server down

![imagen](https://github.com/user-attachments/assets/0a57b2cb-98d3-47fa-9fda-b337292fd8fc)

**Comment by bd808** [comment]
The instance console logs available through horizon.wikimedia.org showed that the OOMKiller had reaped a number of processes including the webservice. I restarted the instance via horizon and then performed the manual application startup process from https://wikitech.wikimedia.org/wiki/Nova_Resource:Petscan#Starting_the_service.

```
Listening on http://0.0.0.0:80
2024-10-25T00:21:47.828312Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646297)
2024-10-25T00:21:52.097668Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646298)
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
2024-10-25T00:23:19.105780Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646299)
2024-10-25T00:23:32.956075Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646300)
2024-10-25T00:23:38.652182Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646301)
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
2024-10-25T00:23:43.142794Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646302)
Error serving connection: hyper::Error(Parse(Uri))
Error serving connection: hyper::Error(Parse(Uri))
```
I do not know if these error messages are meaningful or actionable. Hopefully @magnusmanske will take a look at some point.

**Comment by danielyepezgarces** [comment]
> The instance console logs available through horizon.wikimedia.org showed that the OOMKiller had reaped a number of processes including the webservice. I restarted the instance via horizon and then performed the manual application startup process from https://wikitech.wikimedia.org/wiki/Nova_Resource:Petscan#Starting_the_service.
> 
> ```
> Listening on http://0.0.0.0:80
> 2024-10-25T00:21:47.828312Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646297)
> 2024-10-25T00:21:52.097668Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646298)
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> 2024-10-25T00:23:19.105780Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646299)
> 2024-10-25T00:23:32.956075Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646300)
> 2024-10-25T00:23:38.652182Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646301)
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> 2024-10-25T00:23:43.142794Z  INFO get_or_create_psid_for_query: petscan_rs::app_state: return=Ok(29646302)
> Error serving connection: hyper::Error(Parse(Uri))
> Error serving connection: hyper::Error(Parse(Uri))
> ```
> 
> I do not know if these error messages are meaningful or actionable. Hopefully @magnusmanske will take a look at some point.

Thanks for restart the tool :)

**Comment by danielyepezgarces** [comment]
The tool returns 504 if I make a query that has a SparkQL

**Comment by david-caro** [comment]
I think this is still happening, just restarted the instance (same way as @bd808 mentioned), and it's back up again, but it was showing the OOMKiller logs on the horizon.wikimedia.org log tab for the VM.

**Comment by magnusmanske** [comment]
@david-caro From what I understand, it's [not an easy problem to solve](https://www.reddit.com/r/rust/comments/odlazg/why_rust_panics_on_oom/) on my side [1]. I will try to use more paranoid functions, eg `try_reserve`, but PetScan uses a lot of memory temporarily, it can't always predict the size, and my previous attempts at poor man's disk swapping had unacceptable performance penaltites (plus the VM disk is too small, in addition to the RAM being to small). If you have a simple way to auto-restart the VM when the problem occurs, and to auto-restart PetScan on reboot, that might mitigat things.

**Comment by david-caro** [comment]
>  If you have a simple way to auto-restart the VM when the problem occurs, and to auto-restart PetScan on reboot, that might mitigat things.

Hey, a hackish workaround could be to wrap the execution in a cgroup with the memory limited to less that the VM has, so the VM remains responsive while the program gets OOMd, something like:

```
# one time run
$> cgcreate -g memory:/petscan
$> echo '7G' > /sys/fs/cgroup/petscan/memory.max  # 7G as an example, probably can be tweaked more

# when running petscan (run.sh or similar)
$> cgexec -g memory:/petscan /path/to/petscan_rs
```

You can also get a bigger VM if the memory usage is correct (as in, it's not due to bad requests or can't be improved).


That can also be done with a systemd unit, and that would help too restarting it after reboot and such if that's what you want, something like:
```
[Unit]
Description=Silly service with limited memory
After=network.target

[Service]
Type=exec
ExecStart=/path/to/petscan_rs
# change this to what you want
MemoryMax=7G
Restart=always
StartLimitBurst=20
StartLimitIntervalSec=10

[Install]
WantedBy=default.target
```

Then just `systemctl enable /path/to/servicefile.service`, and you can `systemctl start service` and such after. It could be done on puppet side too if you don't want to have to manually do it every time you create a new VM and such.

**Comment by magnusmanske** [comment]
@david-caro I now have it running as `perscan.service` via sysctrl. I hope this will contain it.
