### ISSUE TITLE
be-tarask wiki doesn't working

### ISSUE THREAD

**Issue by Renessaince** [magnusmanske/petscan_rs#19]
This tool is ignoring be-tarask wiki again. Old tool [works perfect](https://petscan1.wmflabs.org/?language=be_x_old&project=wikipedia&depth=7&categories=%D0%9B%D1%96%D1%82%D0%BE%D1%9E%D1%81%D0%BA%D0%B0-%D0%BC%D0%B0%D1%81%D0%BA%D0%BE%D1%9E%D1%81%D0%BA%D0%B0%D1%8F%20%D0%B2%D0%B0%D0%B9%D0%BD%D0%B0%201512%E2%80%941522%20%D0%B3%D0%B0%D0%B4%D0%BE%D1%9E&combination=subset&negcats=&larger=&smaller=&minlinks=&maxlinks=&before=&after=&max_age=&show_redirects=both&edits%5Bbots%5D=both&edits%5Banons%5D=both&edits%5Bflagged%5D=both&page_image=any&ores_type=any&ores_prob_from=&ores_prob_to=&ores_prediction=any&templates_yes=&templates_any=&templates_no=&outlinks_yes=&outlinks_any=&outlinks_no=&links_to_all=&links_to_any=&links_to_no=&sparql=&manual_list=&manual_list_wiki=&pagepile=&search_query=&search_wiki=&search_max_results=500&wikidata_source_sites=&subpage_filter=either&common_wiki=auto&source_combination=&wikidata_item=no&wikidata_label_language=be_x_old&wikidata_prop_item_use=&wpiu=any&sitelinks_yes=&sitelinks_any=&sitelinks_no=&min_sitelink_count=&max_sitelink_count=&labels_yes=&cb_labels_yes_l=1&langs_labels_yes=&labels_any=&cb_labels_any_l=1&langs_labels_any=&labels_no=&cb_labels_no_l=1&langs_labels_no=&format=wiki&output_compatability=catscan&sortby=incoming_links&sortorder=ascending&regexp_filter=&show_redlinks=on&article_redlinks_only=on&min_redlink_count=1&output_limit=&doit=Do%20it%21&interface_language=en&active_tab=tab_output), but the [same link](https://petscan.wmflabs.org/?language=be_x_old&project=wikipedia&depth=7&categories=%D0%9B%D1%96%D1%82%D0%BE%D1%9E%D1%81%D0%BA%D0%B0-%D0%BC%D0%B0%D1%81%D0%BA%D0%BE%D1%9E%D1%81%D0%BA%D0%B0%D1%8F%20%D0%B2%D0%B0%D0%B9%D0%BD%D0%B0%201512%E2%80%941522%20%D0%B3%D0%B0%D0%B4%D0%BE%D1%9E&combination=subset&negcats=&larger=&smaller=&minlinks=&maxlinks=&before=&after=&max_age=&show_redirects=both&edits%5Bbots%5D=both&edits%5Banons%5D=both&edits%5Bflagged%5D=both&page_image=any&ores_type=any&ores_prob_from=&ores_prob_to=&ores_prediction=any&templates_yes=&templates_any=&templates_no=&outlinks_yes=&outlinks_any=&outlinks_no=&links_to_all=&links_to_any=&links_to_no=&sparql=&manual_list=&manual_list_wiki=&pagepile=&search_query=&search_wiki=&search_max_results=500&wikidata_source_sites=&subpage_filter=either&common_wiki=auto&source_combination=&wikidata_item=no&wikidata_label_language=be_x_old&wikidata_prop_item_use=&wpiu=any&sitelinks_yes=&sitelinks_any=&sitelinks_no=&min_sitelink_count=&max_sitelink_count=&labels_yes=&cb_labels_yes_l=1&langs_labels_yes=&labels_any=&cb_labels_any_l=1&langs_labels_any=&labels_no=&cb_labels_no_l=1&langs_labels_no=&format=wiki&output_compatability=catscan&sortby=incoming_links&sortorder=ascending&regexp_filter=&show_redlinks=on&article_redlinks_only=on&min_redlink_count=1&output_limit=&doit=Do%20it%21&interface_language=en&active_tab=tab_output) in the new tool says «Could not connect to database replica for 'be-x-oldwiki' after 15 attempts». I tried to enter «be_tarask» as well but still the same error.

**Comment by magnusmanske** [comment]
This is now fixed for both `be-x-old` and `be-tarask` with 4ca23a5acb0e9b765cf8c587c4947d50db8ec210.

**Comment by Renessaince** [comment]
Tried with [be-tarask](https://petscan.wmflabs.org/?language=be-tarask&project=wikipedia&depth=7&categories=%D0%9B%D1%96%D1%82%D0%BE%D1%9E%D1%81%D0%BA%D0%B0-%D0%BC%D0%B0%D1%81%D0%BA%D0%BE%D1%9E%D1%81%D0%BA%D0%B0%D1%8F%20%D0%B2%D0%B0%D0%B9%D0%BD%D0%B0%201512%E2%80%941522%20%D0%B3%D0%B0%D0%B4%D0%BE%D1%9E&combination=subset&negcats=&larger=&smaller=&minlinks=&maxlinks=&before=&after=&max_age=&show_redirects=both&edits%5Bbots%5D=both&edits%5Banons%5D=both&edits%5Bflagged%5D=both&page_image=any&ores_type=any&ores_prob_from=&ores_prob_to=&ores_prediction=any&templates_yes=&templates_any=&templates_no=&outlinks_yes=&outlinks_any=&outlinks_no=&links_to_all=&links_to_any=&links_to_no=&sparql=&manual_list=&manual_list_wiki=&pagepile=&search_query=&search_wiki=&search_max_results=500&wikidata_source_sites=&subpage_filter=either&common_wiki=auto&source_combination=&wikidata_item=no&wikidata_label_language=be_x_old&wikidata_prop_item_use=&wpiu=any&sitelinks_yes=&sitelinks_any=&sitelinks_no=&min_sitelink_count=&max_sitelink_count=&labels_yes=&cb_labels_yes_l=1&langs_labels_yes=&labels_any=&cb_labels_any_l=1&langs_labels_any=&labels_no=&cb_labels_no_l=1&langs_labels_no=&format=wiki&output_compatability=catscan&sortby=incoming_links&sortorder=ascending&regexp_filter=&show_redlinks=on&article_redlinks_only=on&min_redlink_count=1&output_limit=&doit=Do%20it%21&interface_language=en&active_tab=tab_output), [be-x-old](https://petscan.wmflabs.org/?language=be-x-old&project=wikipedia&depth=7&categories=%D0%9B%D1%96%D1%82%D0%BE%D1%9E%D1%81%D0%BA%D0%B0-%D0%BC%D0%B0%D1%81%D0%BA%D0%BE%D1%9E%D1%81%D0%BA%D0%B0%D1%8F%20%D0%B2%D0%B0%D0%B9%D0%BD%D0%B0%201512%E2%80%941522%20%D0%B3%D0%B0%D0%B4%D0%BE%D1%9E&combination=subset&negcats=&larger=&smaller=&minlinks=&maxlinks=&before=&after=&max_age=&show_redirects=both&edits%5Bbots%5D=both&edits%5Banons%5D=both&edits%5Bflagged%5D=both&page_image=any&ores_type=any&ores_prob_from=&ores_prob_to=&ores_prediction=any&templates_yes=&templates_any=&templates_no=&outlinks_yes=&outlinks_any=&outlinks_no=&links_to_all=&links_to_any=&links_to_no=&sparql=&manual_list=&manual_list_wiki=&pagepile=&search_query=&search_wiki=&search_max_results=500&wikidata_source_sites=&subpage_filter=either&common_wiki=auto&source_combination=&wikidata_item=no&wikidata_label_language=be_x_old&wikidata_prop_item_use=&wpiu=any&sitelinks_yes=&sitelinks_any=&sitelinks_no=&min_sitelink_count=&max_sitelink_count=&labels_yes=&cb_labels_yes_l=1&langs_labels_yes=&labels_any=&cb_labels_any_l=1&langs_labels_any=&labels_no=&cb_labels_no_l=1&langs_labels_no=&format=wiki&output_compatability=catscan&sortby=incoming_links&sortorder=ascending&regexp_filter=&show_redlinks=on&article_redlinks_only=on&min_redlink_count=1&output_limit=&doit=Do%20it%21&interface_language=en&active_tab=tab_output), [be_tarask](https://petscan.wmflabs.org/?language=be_tarask&project=wikipedia&depth=7&categories=%D0%9B%D1%96%D1%82%D0%BE%D1%9E%D1%81%D0%BA%D0%B0-%D0%BC%D0%B0%D1%81%D0%BA%D0%BE%D1%9E%D1%81%D0%BA%D0%B0%D1%8F%20%D0%B2%D0%B0%D0%B9%D0%BD%D0%B0%201512%E2%80%941522%20%D0%B3%D0%B0%D0%B4%D0%BE%D1%9E&combination=subset&negcats=&larger=&smaller=&minlinks=&maxlinks=&before=&after=&max_age=&show_redirects=both&edits%5Bbots%5D=both&edits%5Banons%5D=both&edits%5Bflagged%5D=both&page_image=any&ores_type=any&ores_prob_from=&ores_prob_to=&ores_prediction=any&templates_yes=&templates_any=&templates_no=&outlinks_yes=&outlinks_any=&outlinks_no=&links_to_all=&links_to_any=&links_to_no=&sparql=&manual_list=&manual_list_wiki=&pagepile=&search_query=&search_wiki=&search_max_results=500&wikidata_source_sites=&subpage_filter=either&common_wiki=auto&source_combination=&wikidata_item=no&wikidata_label_language=be_x_old&wikidata_prop_item_use=&wpiu=any&sitelinks_yes=&sitelinks_any=&sitelinks_no=&min_sitelink_count=&max_sitelink_count=&labels_yes=&cb_labels_yes_l=1&langs_labels_yes=&labels_any=&cb_labels_any_l=1&langs_labels_any=&labels_no=&cb_labels_no_l=1&langs_labels_no=&format=wiki&output_compatability=catscan&sortby=incoming_links&sortorder=ascending&regexp_filter=&show_redlinks=on&article_redlinks_only=on&min_redlink_count=1&output_limit=&doit=Do%20it%21&interface_language=en&active_tab=tab_output), but still the same error.

**Comment by magnusmanske** [comment]
New fix, all your three links now work.
