### ISSUE TITLE
Support user sessions going in/out of PetScan from other tools

### ISSUE THREAD

**Issue by eggpi** [magnusmanske/petscan_rs#2]
As discussed in Wikimania, Citation Hunt has a flow where users click a link to PetScan, come up with a query, and are then supposed to navigate back to the same CH tab and paste the ID of the resulting PS query.

It would be neat if we could integrate the two tools a little more closely. For example, CH would have a link to:

<pre>
https://petscan.wmflabs.org?language=en&depth=5&<b>toolname</b>=Citation%20Hunt&<b>toolurl</b>=&ltsome opaque url&gt
</pre>

And PS would have a link for returning to the tool, which, when clicked, sends the user to:

<pre>
https://&ltsome opaque url&gt?psid=123456
</pre>

when they are done with their query.

**Comment by magnusmanske** [comment]
Implemented with ce14e78e6e3368cbf103aa5107777ac6d44e87b8 .

See documentation at https://meta.wikimedia.org/wiki/PetScan#Referrer
