### ISSUE TITLE
missing urlencoding for fields labels_yes, labels_any, labels_no

### ISSUE THREAD

**Issue by MisterSynergy** [magnusmanske/petscan_rs#22]
Looks like the fields `labels_yes`, `labels_any`, and `labels_no` only work if their content is *not* properly URL-encoded. That means that in particular the suggested SQL LIKE operator `%` must not be URL-encoded to `%25` in order to have a working query.

The listed input fields should *only* work if the field content is properly URL-encoded transmitted.

**Comment by magnusmanske** [comment]
Example?

Counter-example with `%25`:
http://petscan.wmflabs.org/?project=wikipedia&edits%5Bbots%5D=both&ns%5B0%5D=1&search_max_results=500&active_tab=tab_wikidata&edits%5Bflagged%5D=both&language=en&labels_yes=Magnus%20%25&edits%5Banons%5D=both&interface_language=en&doit=

**Comment by MisterSynergy** [comment]
Thanks for looking at this issue. Unfortunately, I do not get a psid as my queries do not finish.

Use case is: select a Wikipedia category in the "Categories" tab, and output all category members whose connected Wikidata item do *not* have a description in a given language. Specifically in the "Wikidata" tab of the Petscan web UI, I select "Only pages with item", and "Has none of these labels" : "%" (i.e. percent sign only, no quotes), and a language code in the field below.

I meanwhile realized that I might have misunderstood how the % character in SQL LIKE operators works: it means "zero or more characters", not "one or more characters" as I initially assumed while creating this issue. Probably "Has none of these labels" : "%" does not work at all as desired. Yet it is not cool that the tool just loads endlessly without ever providing a response.

**Comment by magnusmanske** [comment]
WMF is changing the label/alias/description storage. I have now switched to the new system, even though it might not be fully seeded yet (just a matter of time).

Your query [now works](https://petscan.wmflabs.org/?psid=12115807). You don't need to set "only pages with items", this will be enforced by using the label filter anyway.
