### ISSUE TITLE
This is a new version of PetScan. The previous version is here -->  redirected to same page

### ISSUE THREAD

**Issue by jdvala** [magnusmanske/petscan_rs#23]
The landing page of the petscan has a dialog box which informs about the new version of the service available but unfortunately it doesn't redirect to the new version.

Cause:
Upon inspecting the page,
```html
<div class="alert alert-primary" role="alert">
This is a new version of PetScan. The previous version is <a href="http://petscan1.wmflabs.org/">here</a>.
</div>
```
I found that the redirection has same hyperlink as the old version

**Comment by jdvala** [comment]
If this is the new version, then I suggest removing this code https://github.com/magnusmanske/petscan_rs/blob/e0ef8dfd316629d1c14b226220026f141fa681fe/html/index.html#L146

I can make a pull request but need a confirmation that this is the latest version

**Comment by magnusmanske** [comment]
I don't understand the issue.
https://petscan.wmflabs.org/ says "The previous version is here.", linking to http://petscan1.wmflabs.org/ (note the "1").

That says it's the old version, "The current version of PetScan is here. ", linking to http://petscan.wmflabs.org/ (without the "1").

What is wrong with that?

**Comment by jdvala** [comment]
My bad. I had failed to notice the change.
