### ISSUE TITLE
UI is not RTL compatible

### ISSUE THREAD

**Issue by yarons** [magnusmanske/petscan_rs#24]
Switching to Hebrew changes the labels but it should also switch directionality of the UI.

An explanation by Mozilla:
https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/

**Comment by magnusmanske** [comment]
Honestly, I don't have the bandwidth nor the knowledge to do this.
PRs welcome.

**Comment by magnusmanske** [comment]
If you can give me the CSS required, I might be able to patch this from the interface langauage and the "rtl" info here: https://www.wikidata.org/w/api.php?action=sitematrix

**Comment by yarons** [comment]
@magnusmanske I like this idea, but maybe you can go further and just specify whether this language is RTL or not and configure the RTL CSS in a different meta location, as you please, I truly don't mind.

**Comment by magnusmanske** [comment]
Got the detection running. What do I need to do on the CSS? Just `<html dir="rtl">`?

**Comment by yarons** [comment]
It may break some things, the original approach is to add this and then fix
all the glitches manually.

Usually I'm adding these changes with !important and it does the trick.

**Comment by magnusmanske** [comment]
[I did what I could](https://petscan.wmflabs.org/?interface_language=ar)

**Comment by yarons** [comment]
This is awesome!
The only thing misaligned is the titles and checkboxes in "Templates&links", and the mobile version has some glitches but other than that you did a fantastic job, thank you!

**Comment by magnusmanske** [comment]
I'm closing this issue now.
If you have a patch for the remaining glitches, please re-open, or open a new issue.

**Comment by yarons** [comment]
Yeah sure, I'll give you a heads up once I'll investigate this further, BTW, where is this css file?

**Comment by magnusmanske** [comment]
Not a separate CSS file at the moment, rather the <style> section in https://github.com/magnusmanske/petscan_rs/blob/master/html/index.html

**Comment by yarons** [comment]
I know some communities that might consider your execution for that but luckily I'm not that kind of person, will you consider separating it or shall I work with that for the meanwhile?
