### ISSUE TITLE
Provide guidance for sparql as input

### ISSUE THREAD

**Issue by vojtechhuser** [magnusmanske/petscan_rs#26]
The manual does not specify what the SPARQL query should look like. Provide one example that uses it.

E.g., can it only have ?item in select or can it have 20 columns?

I need query that does
this as input

SELECT 
?item {
  ?item wdt:P31 wd:Q15636229 . #surg proc
  ?sitelinkEn schema:about ?item ; schema:isPartOf <https://en.wikipedia.org/> 
  }

and is WP page is not using template medical resources. and I can't get it to work. Manual is not detailed enough to figure it out.

**Comment by magnusmanske** [comment]
The manual is a wiki; be bold in updating pages!
