### ISSUE TITLE
Edit date limit fail

### ISSUE THREAD

**Issue by magnusmanske** [magnusmanske/petscan_rs#27]
From [Epìdosis](https://www.wikidata.org/wiki/User:Ep%C3%ACdosis) on [Talk page](https://www.wikidata.org/wiki/Topic:Vcrvh11fr37r1ujs):
Hi! I've just tried [this PetScan query](http://petscan.wmflabs.org/?psid=14289681) looking for items with  instance of (P31) human (Q5) and Open Library ID (P648) edited after yesterday, but the results are 120k - all items containing those statements are included, whilst the specification "edited after yesterday" is completely ignored. Could you have a look? Thank you very much!

**Comment by wargo32** [comment]
I have problems with before-after by edit date.
When last edit sorted descending, "before" works only with "after". When ascending, "before" not working.
Do filtering by date work on "touched" or last revision version?

**Comment by magnusmanske** [comment]
Fixed the original issue.

@wargo32 if you still have your problem, please open a new issue, preferably with an example.
