### ISSUE TITLE
Wikidata links served in place of sitelinks

### ISSUE THREAD

**Issue by Pikse** [magnusmanske/petscan_rs#30]
If I choose "Add items, where available" and fill in "Uses items/props" then this results in "Title" column having links to Wikidata items and "Item" column being empty (which doesn't seem right):

http://petscan.wmflabs.org/?common_wiki_other=&edits%5Bflagged%5D=both&edits%5Bbots%5D=both&cb_labels_no_l=1&search_max_results=500&edits%5Banons%5D=both&wikidata_item=any&project=wikipedia&cb_labels_any_l=1&ns%5B0%5D=1&interface_language=en&language=et&categories=Mustam%C3%A4e%20linnaosa%20t%C3%A4navad&wikidata_prop_item_use=P31&cb_labels_yes_l=1&active_tab=tab_wikidata&doit=

I assume it should work as in old version, where "Title" column has sitelinks (links to Wikipedia articles) and links to Wikidata items are in "Item" column:

http://petscan1.wmflabs.org/?active_tab=tab_wikidata&cb_labels_yes_l=1&search_max_results=500&categories=Mustam%C3%A4e%20linnaosa%20t%C3%A4navad&interface_language=en&project=wikipedia&edits[flagged]=both&cb_labels_no_l=1&wikidata_prop_item_use=P31&wikidata_item=any&edits[bots]=both&language=et&edits[anons]=both&cb_labels_any_l=1&ns[0]=1&&doit=

Both sitelinks and Wikidata links being served was a useful feature and so I hope that sitelinks aren't intentionally gone in new version.

**Comment by magnusmanske** [comment]
I'll have a look.
Until then, you can always "force" the sitelinks under "Other sources/Use Wiki" => "From categories"

**Comment by magnusmanske** [comment]
This is fixed now.
