### ISSUE TITLE
Remove left-to-right marks in category strings

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/petscan_rs#32]
Petscan produces 0 results when there's a left-to-right mark left in a category string that has been cut & pasted from somewhere in wikimedia - such marks seem prevelant on wikimedia sites (allegedly).
 
See https://www.wikidata.org/w/index.php?title=Wikidata:Project_chat&oldid=1100232633#PetScan_problem for example of this issue tripping a user.

**Comment by magnusmanske** [comment]
Resolved with 0f9e8e5e
