### ISSUE TITLE
Categories starting with a small-caps in Wiktionary

### ISSUE THREAD

**Issue by Sinfadiel** [magnusmanske/petscan_rs#34]
Hello :)

Petscan do not work when a category start with a small-caps, probably because of case-blindness of Wikipedia. Sadly, in French, we write languages names with a small caps, so we have categories such as "[français de France](https://fr.wiktionary.org/wiki/Cat%C3%A9gorie:fran%C3%A7ais_de_France)", "[français du Canada](https://fr.wiktionary.org/wiki/Cat%C3%A9gorie:fran%C3%A7ais_du_Canada)" for France French, Canadian French. 

When we try Petscan with those categories it display [no results](https://petscan.wmflabs.org/?manual_list_wiki=&cb_labels_no_l=1&edits%5Banons%5D=both&cb_labels_yes_l=1&search_max_results=500&interface_language=fr&project=wiktionary&edits%5Bbots%5D=both&cb_labels_any_l=1&categories=Lexique%20en%20fran%C3%A7ais%20de%20l%E2%80%99histoire%0Afran%C3%A7ais%20de%20France&language=fr&edits%5Bflagged%5D=both&langs_labels_no=&doit=&interface_language=fr). Is it possible to fix it with a specific exception for French Wiktionary or a more general answer?

Thank you in advance!

**Comment by magnusmanske** [comment]
Category and Template namespaces are now automatically case-(in)sensitive, as set on the respective wiki.
