### ISSUE TITLE
Ever since the new version came out, I cannot use it.

### ISSUE THREAD

**Issue by SednaBoo** [magnusmanske/petscan_rs#39]
I was holding on to the old version as long as I could, but looks like the plug was finally pulled and I'm stuck.  Same queries I used to run all the time now just give 504 errors.  The ones I had been using were:

*[https://petscan1.wmflabs.org/?language=en&project=wikipedia&ns%5B0%5D=1&ns%5B118%5D=1&templates_any=Virusbox%0D%0ATaxonbar%0D%0ATaxobox%0D%0ASubspeciesbox%0D%0ASpeciesbox%0D%0AParaphyletic%20group%0D%0AOobox%0D%0AMissing-taxobox%0D%0AInfraspeciesbox%0D%0AIchnobox%0D%0AHybridbox%2Flua%0D%0AHybridbox%0D%0ABiota%20infobox%0D%0AAutomatic%20taxobox&templates_no=WikiProject%20Palaeontology%0D%0AWikiProject%20Marine%20life%0D%0AWikiProject%20Viruses%0D%0AWikiProject%20Turtles%0D%0AWikiProject%20Spiders%0D%0AWikiProject%20Sharks%0D%0AWikiProject%20Rodents%0D%0AWikiProject%20Pterosaurs%0D%0AWikiProject%20Pteridophytes%0D%0AWikiProject%20Primates%0D%0AWikiProject%20Poultry%0D%0AWikiProject%20Plants%0D%0AWikiProject%20Palaeontology%2FLobe-Fins%0D%0AWikiProject%20Microbiology%0D%0AWikiProject%20Mantodea%0D%0AWikiProject%20Mammals%2FBats%20Task%20Force%0D%0AWikiProject%20Mammals%0D%0AWikiProject%20Lepidoptera%0D%0AWikiProject%20Insects%0D%0AWikiProject%20Hypericaceae%0D%0AWikiProject%20Gastropods%0D%0AWikiProject%20Fungi%0D%0AWikiProject%20Fishes%0D%0AWikiProject%20Equine%0D%0AWikiProject%20Dogs%0D%0AWikiProject%20Diptera%0D%0AWikiProject%20Dinosaurs%0D%0AWikiProject%20Cetaceans%0D%0AWikiProject%20Cephalopods%0D%0AWikiProject%20Cats%0D%0AWikiProject%20Carnivorous%20plants%0D%0AWikiProject%20Bivalves%0D%0AWikiProject%20Birds%0D%0AWikiProject%20Beetles%0D%0AWikiProject%20Banksia%0D%0AWikiProject%20Arthropods%0D%0AWikiProject%20Animals%0D%0AWikiProject%20Amphibians%20and%20Reptiles%0D%0AWikiProject%20Algae%0D%0A&templates_use_talk_no=on&search_max_results=500&sortby=title&sortorder=descending&add_image=on&interface_language=en&active_tab=&doit= Taxon pages not tagged in WP ToL clade projects (with WPPaleontology and WPMarine life)] - Should be pretty empty
*[https://petscan1.wmflabs.org/?language=en&project=wikipedia&ns%5B0%5D=1&ns%5B118%5D=1&templates_any=Virusbox%0D%0ATaxonbar%0D%0ATaxobox%0D%0ASubspeciesbox%0D%0ASpeciesbox%0D%0AParaphyletic%20group%0D%0AOobox%0D%0AMissing-taxobox%0D%0AInfraspeciesbox%0D%0AIchnobox%0D%0AHybridbox%2Flua%0D%0AHybridbox%0D%0ABiota%20infobox%0D%0AAutomatic%20taxobox&templates_no=WikiProject%20Palaeontology%0D%0AWikiProject%20Viruses%0D%0AWikiProject%20Turtles%0D%0AWikiProject%20Spiders%0D%0AWikiProject%20Sharks%0D%0AWikiProject%20Rodents%0D%0AWikiProject%20Pterosaurs%0D%0AWikiProject%20Pteridophytes%0D%0AWikiProject%20Primates%0D%0AWikiProject%20Poultry%0D%0AWikiProject%20Plants%0D%0AWikiProject%20Palaeontology%2FLobe-Fins%0D%0AWikiProject%20Microbiology%0D%0AWikiProject%20Mantodea%0D%0AWikiProject%20Mammals%2FBats%20Task%20Force%0D%0AWikiProject%20Mammals%0D%0AWikiProject%20Lepidoptera%0D%0AWikiProject%20Insects%0D%0AWikiProject%20Hypericaceae%0D%0AWikiProject%20Gastropods%0D%0AWikiProject%20Fungi%0D%0AWikiProject%20Fishes%0D%0AWikiProject%20Equine%0D%0AWikiProject%20Dogs%0D%0AWikiProject%20Diptera%0D%0AWikiProject%20Dinosaurs%0D%0AWikiProject%20Cetaceans%0D%0AWikiProject%20Cephalopods%0D%0AWikiProject%20Cats%0D%0AWikiProject%20Carnivorous%20plants%0D%0AWikiProject%20Bivalves%0D%0AWikiProject%20Birds%0D%0AWikiProject%20Beetles%0D%0AWikiProject%20Banksia%0D%0AWikiProject%20Arthropods%0D%0AWikiProject%20Animals%0D%0AWikiProject%20Amphibians%20and%20Reptiles%0D%0AWikiProject%20Algae%0D%0A&templates_use_talk_no=on&search_max_results=500&sortby=title&sortorder=descending&add_image=on&interface_language=en&active_tab=tab_templates_n_links&doit= Taxon pages not tagged in WP ToL clade projects (with WPPaleontology)] - ~481 results
*[https://petscan1.wmflabs.org/?language=en&project=wikipedia&ns%5B0%5D=1&ns%5B118%5D=1&templates_any=Virusbox%0D%0ATaxonbar%0D%0ATaxobox%0D%0ASubspeciesbox%0D%0ASpeciesbox%0D%0AParaphyletic%20group%0D%0AOobox%0D%0AMissing-taxobox%0D%0AInfraspeciesbox%0D%0AIchnobox%0D%0AHybridbox%2Flua%0D%0AHybridbox%0D%0ABiota%20infobox%0D%0AAutomatic%20taxobox&templates_no=WikiProject%20Marine%20life%0D%0AWikiProject%20Viruses%0D%0AWikiProject%20Turtles%0D%0AWikiProject%20Spiders%0D%0AWikiProject%20Sharks%0D%0AWikiProject%20Rodents%0D%0AWikiProject%20Pterosaurs%0D%0AWikiProject%20Pteridophytes%0D%0AWikiProject%20Primates%0D%0AWikiProject%20Poultry%0D%0AWikiProject%20Plants%0D%0AWikiProject%20Palaeontology%2FLobe-Fins%0D%0AWikiProject%20Microbiology%0D%0AWikiProject%20Mantodea%0D%0AWikiProject%20Mammals%2FBats%20Task%20Force%0D%0AWikiProject%20Mammals%0D%0AWikiProject%20Lepidoptera%0D%0AWikiProject%20Insects%0D%0AWikiProject%20Hypericaceae%0D%0AWikiProject%20Gastropods%0D%0AWikiProject%20Fungi%0D%0AWikiProject%20Fishes%0D%0AWikiProject%20Equine%0D%0AWikiProject%20Dogs%0D%0AWikiProject%20Diptera%0D%0AWikiProject%20Dinosaurs%0D%0AWikiProject%20Cetaceans%0D%0AWikiProject%20Cephalopods%0D%0AWikiProject%20Cats%0D%0AWikiProject%20Carnivorous%20plants%0D%0AWikiProject%20Bivalves%0D%0AWikiProject%20Birds%0D%0AWikiProject%20Beetles%0D%0AWikiProject%20Banksia%0D%0AWikiProject%20Arthropods%0D%0AWikiProject%20Animals%0D%0AWikiProject%20Amphibians%20and%20Reptiles%0D%0AWikiProject%20Algae%0D%0A&templates_use_talk_no=on&search_max_results=500&sortby=title&sortorder=descending&add_image=on&interface_language=en&active_tab=&doit= Taxon pages not tagged in WP ToL clade projects (with WPMarine life)] - ~936 results

obviously dropping the '1' does not work now either.    I also try doing new searches by hand and they give the 504s.  Basically, for the first version, I want all articles that have one of the taxobox templates:
Virusbox
Taxonbar
Taxobox
Subspeciesbox
Speciesbox
Paraphyletic group
Oobox
Missing-taxobox
Infraspeciesbox
Ichnobox
Hybridbox/lua
Hybridbox
Biota infobox
Automatic taxobox

but are not yet tagged with any of the Tree of Life talk page templates on theit talk pages:
WikiProject Viruses
WikiProject Turtles
WikiProject Tree of Life
WikiProject Spiders
WikiProject Sharks
WikiProject Rodents
WikiProject Primates
WikiProject Plants
WikiProject Palaeontology
WikiProject Mammals
WikiProject Microbiology
WikiProject Marine life
WikiProject Mammals/Bats Task Force
WikiProject Mammals
WikiProject Lepidoptera
WikiProject Insects
WikiProject Hypericaceae
WikiProject Gastropods
WikiProject Fungi
WikiProject Fishes
WikiProject Equine
WikiProject Dogs
WikiProject Diptera
WikiProject Dinosaurs
WikiProject Cetaceans
WikiProject Cephalopods
WikiProject Cats
WikiProject Carnivorous plants
WikiProject Cannabis
WikiProject Bivalves
WikiProject Birds
WikiProject Beetles
WikiProject Banksia
WikiProject Arthropods
WikiProject Plants
WikiProject Animals
WikiProject Amphibians and Reptiles
WikiProject Algae

Other folks in the same project seem to have similar issues.  The kind folks on IRC discouraged me from posting this earlier, but it's been several months.  I never got it to work on the new version, and kept waiting for all the kinks to get worked out. I really liked the tool, but it seems like you're pretty busy, so this may be a waste of time.  But thought I should atleast make an note of it.

**Comment by magnusmanske** [comment]
This should be fixed now ([example](https://petscan.wmflabs.org/?language=en&project=wikipedia&ns%5B0%5D=1&ns%5B118%5D=1&templates_any=Virusbox%0D%0ATaxonbar%0D%0ATaxobox%0D%0ASubspeciesbox%0D%0ASpeciesbox%0D%0AParaphyletic%20group%0D%0AOobox%0D%0AMissing-taxobox%0D%0AInfraspeciesbox%0D%0AIchnobox%0D%0AHybridbox%2Flua%0D%0AHybridbox%0D%0ABiota%20infobox%0D%0AAutomatic%20taxobox&templates_no=WikiProject%20Palaeontology%0D%0AWikiProject%20Marine%20life%0D%0AWikiProject%20Viruses%0D%0AWikiProject%20Turtles%0D%0AWikiProject%20Spiders%0D%0AWikiProject%20Sharks%0D%0AWikiProject%20Rodents%0D%0AWikiProject%20Pterosaurs%0D%0AWikiProject%20Pteridophytes%0D%0AWikiProject%20Primates%0D%0AWikiProject%20Poultry%0D%0AWikiProject%20Plants%0D%0AWikiProject%20Palaeontology%2FLobe-Fins%0D%0AWikiProject%20Microbiology%0D%0AWikiProject%20Mantodea%0D%0AWikiProject%20Mammals%2FBats%20Task%20Force%0D%0AWikiProject%20Mammals%0D%0AWikiProject%20Lepidoptera%0D%0AWikiProject%20Insects%0D%0AWikiProject%20Hypericaceae%0D%0AWikiProject%20Gastropods%0D%0AWikiProject%20Fungi%0D%0AWikiProject%20Fishes%0D%0AWikiProject%20Equine%0D%0AWikiProject%20Dogs%0D%0AWikiProject%20Diptera%0D%0AWikiProject%20Dinosaurs%0D%0AWikiProject%20Cetaceans%0D%0AWikiProject%20Cephalopods%0D%0AWikiProject%20Cats%0D%0AWikiProject%20Carnivorous%20plants%0D%0AWikiProject%20Bivalves%0D%0AWikiProject%20Birds%0D%0AWikiProject%20Beetles%0D%0AWikiProject%20Banksia%0D%0AWikiProject%20Arthropods%0D%0AWikiProject%20Animals%0D%0AWikiProject%20Amphibians%20and%20Reptiles%0D%0AWikiProject%20Algae%0D%0A&templates_use_talk_no=on&search_max_results=500&sortby=title&sortorder=descending&add_image=on&interface_language=en&active_tab=&doit=)).

Why would anyone _ever_ discourage you from filing a bug report? If I'm busy, it might take a while, but I'd get around to it eventually, especially if it's breaking previous functionality, as in this case.
