### ISSUE TITLE
page not visible though results have been returned

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/petscan_rs#4]
I'm getting blank pages back in firefox & safari for http://petscan.wmflabs.org/?psid=7818328 ... petscan has returned results, but neither browser is rendering the code.

**Comment by Tagishsimon** [comment]
Screengrabs: https://twitter.com/Tagishsimon/status/1164296976525156353

**Comment by magnusmanske** [comment]
Fixed
