### ISSUE TITLE
New pages search broken?

### ISSUE THREAD

**Issue by Nirvanchik** [magnusmanske/petscan_rs#44]
Petscan, when you request new pages (with a flag "Only pages created during the above time window " enabled) currently gives only 1 page, and this page is not the newest (26-28 Febrary).

This behavior started today in the morning.

Example links:

https://petscan.wmflabs.org/?referrer_url=&cb_labels_any_l=1&edits%5Bflagged%5D=both&interface_language=en&edits%5Banons%5D=both&language=ru&cb_labels_no_l=1&sortorder=descending&depth=6&max_age=500&only_new=on&ns%5B0%5D=1&project=wikipedia&edits%5Bbots%5D=both&categories=Узбекистан&search_max_results=500&cb_labels_yes_l=1&combination=union&&doit=

https://petscan.wmflabs.org/?ns%5B0%5D=1&language=ru&depth=6&only_new=on&combination=union&max_age=720&categories=Олимпийские%20игры&interface_language=en&sortorder=descending&project=wikipedia&negcats=Олимпийские%20виды%20спорта&doit=

**Comment by magnusmanske** [comment]
I think I fixed it, please check!

**Comment by Nirvanchik** [comment]
Yes, now it looks better (web tool).
Tomorrow morning will see how bot works..

**Comment by Nirvanchik** [comment]
Works fine!
