### ISSUE TITLE
Petscan apparently stopped working

### ISSUE THREAD

**Issue by Speravir** [magnusmanske/petscan_rs#45]
… at least for Commons. User D-Kuru noticed this and asked at the [Commons:Village pump](https://commons.wikimedia.org/w/index.php?oldid=402842638#PetScan_question). I must confirm this.

Cf. https://petscan.wmflabs.org/?psid=15773910 – this gets 0 results in the moment, but should at least find these two images (I didn’t check whether there are more): [Beispiel.jpg](https://commons.wikimedia.org/wiki/File:Beispiel.jpg) and [Beispiel.png](https://commons.wikimedia.org/wiki/File:Beispiel.png).

**Comment by magnusmanske** [comment]
That query
* uses category "Exampe images" instead of "Example images"
* uses namespace Gallery (0) instead of Files
If you fix the errors in the query, [it works](https://petscan.wmflabs.org/?psid=15776540).

**Comment by Speravir** [comment]
OMG, I’m so sorry. How could I overlook this …

**Comment by magnusmanske** [comment]
No problem, that happens :-)
