### ISSUE TITLE
sorting by date 

### ISSUE THREAD

**Issue by magnusmanske** [magnusmanske/petscan_rs#46]
Originally [here](https://bitbucket.org/magnusmanske/petscan/issues/161/petscan-sorting-by-date).

**Comment by magnusmanske** [comment]
I recently (~a week?) changed the "last changed" date internally from the "last touched" entry in the page table, to the timestamp of the current revision. "last touched" can be newer than current revision timestamp, eg when a template was updated and the change rolled out to the page, without an actual edit to the page.

The current implementation should reflect actual revision changed on Wikipedia etc.

Please re-open this issue if you can find an example where it does not work correctly.

**Comment by masegand** [comment]
Q1683066 was edited today, but showed up with 20191009200028 timestamp. Though there is a replag 

wikidatawiki.{analytics,web}.db.svc.eqiad.wmflabs | s8 | 40033.9990 | 11:07:13
 
currently
