### ISSUE TITLE
petscan sorting by date

### ISSUE THREAD

**Issue by masegand** [magnusmanske/petscan_rs#47]
for example Q2514091 has many recent updates but shows up with 20180128203142 timestamp.

_Originally posted by @masegand in https://github.com/magnusmanske/petscan_rs/issues/46#issuecomment-599110376_

**Comment by magnusmanske** [comment]
Now shows for me with 20200326131043.

Might have been the replag you mentioned. At this time, Q2581323 was on top of Recent Changes but it already shows with proper timestamp.

I'll close this one, please re-open with more examples that can't be attributed to replag (which I can do nothing about).
