### ISSUE TITLE
Chrome blocks WiDaR cookie it seems

### ISSUE THREAD

**Issue by pangoSE** [magnusmanske/petscan_rs#49]
I get this error with petscan: 
A cookie associated with a cross-site resource at http://tools.wmflabs.org/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by VojtechDostal** [comment]
Today I could not authorize Widar in Chrome for Petscan despite repeated attempts. Maybe this has something to do with it. It works in Microsoft Edge.

**Comment by Sadads** [comment]
I believe this is related to https://phabricator.wikimedia.org/T158604

**Comment by magnusmanske** [comment]
The WiDaR call in JS was a leftover from a previous setup. I have removed the call, and it should not be an issue for PetScan. No cross-site cookies should be set/used.
