### ISSUE TITLE
Checkbox "Only pages created during the above time window" is not working 

### ISSUE THREAD

**Issue by PiotrGackowski** [magnusmanske/petscan_rs#5]
Here 
https://petscan.wmflabs.org/?language=pl&project=wikipedia&depth=99&categories=Okr%C4%99ty&max_age=120&only_new=on&search_max_results=500&sortby=date&sortorder=descending&interface_language=en&active_tab=&doit=
should be list of "articles created in category:Okręty in last 120 hours".  (basicly its "show me all new warships-related articles")

But I receive list of all edits in this category. On "Page properties" tab there is a checkbox "Only pages created during the above time window" but its not working (turning it on and off give the same results).

Checked on current versions of Firefox and Chrome on Windows 10

**Comment by magnusmanske** [comment]
This should be fixed now.

**Comment by PiotrGackowski** [comment]
LGTM
