### ISSUE TITLE
Today HTTP 504 again: notification from Pywikibot tests?

### ISSUE THREAD

**Issue by dvorapa** [magnusmanske/petscan_rs#52]
Hi, reaching from Pywikibot team!

In Pywikibot tests we regularly test Petscan. As Petscan has been unstable so many times in the last months, in Pywikibot we already implemented some workarounds not to fail tests, just skip them. Today, Petscan is failing with 504 again as many times lately and I got an idea:

Would it be helpful to catch such errors and send some kind of hook or notification from Pywikibot tests if tests find out Petscan is down?

**Comment by dvorapa** [comment]
It can be anything: editing a MediaWiki page, sending an e-mail, posting to IRC, whatever is suitable.

**Comment by magnusmanske** [comment]
Should work more reliably now.
