### ISSUE TITLE
Petscan is down every day (504 Gateway Time-out)

### ISSUE THREAD

**Issue by Nirvanchik** [magnusmanske/petscan_rs#55]
Petscan is down most of the time recently.
Now it's down, and it was down in the night.
And couple of days ago it was down too in the night.

With such bad stability I'm not sure of continuing using it. Our bot does everyday jobs that rely on Petscan. Petscan was I great helper there doing 80% of work and giving good speed. But with such instability it's useless and I'm starting to develop solution without Petscan. Sorry.

**Comment by Nirvanchik** [comment]
At the same time I still have a hope about Petscan. I'll try to get into Labs and see what happens inside if I manage to get access there. May be I can be helpful to bring it up but I'm not sure.

**Comment by Nirvanchik** [comment]
I searched petscan admin account on https://tools.wmflabs.org/admin/tools
and couldn't find anything.

And also I found this:
https://tools.wmflabs.org/catscan2/notice.html

And this is very sad :(

**Comment by Nirvanchik** [comment]
No petscan on https://toolsadmin.wikimedia.org/tools/ either :(

**Comment by Vort** [comment]
No 504 error right now. Connection is just hanging forever.

**Comment by WilliamAvery** [comment]
> 
> 
> No petscan on https://toolsadmin.wikimedia.org/tools/ either :(

Petscan is a separate project from Tools, with its own servers, like Phabricator

**Comment by mgoose109** [comment]
> At the same time I still have a hope about Petscan. I'll try to get into Labs and see what happens inside if I manage to get access there. May be I can be helpful to bring it up but I'm not sure.

Hi! I've managed to get the code to run, but I don't have a Tooolforge account so can't access the replicas of the database and I couldn't really host the website either. Maybe you or someone else could help?

**Comment by mgoose109** [comment]
That is, some older c++ code. I didn't realize this rust version existed as well.

**Comment by magnusmanske** [comment]
Should be working better now.
