### ISSUE TITLE
Request does not return a correct answer

### ISSUE THREAD

**Issue by cjerabek** [magnusmanske/petscan_rs#56]
http://tools.wmflabs.org/catscan2/catscan2.php?language=fr&depth=4&categories={{urlencode:Photographe russe}}&negcats={{urlencode:Évaluation des articles du projet Photographie}}&interface_language=fr&doit=1

The excluding category is not taken into account

**Comment by cjerabek** [comment]
Maybe the result is correct because the depth of 4 is not taken into account in the negcat ? In this case it would be nice to enhance the feature ?

**Comment by magnusmanske** [comment]
The category tree "Évaluation des articles du projet Photographie" contains the _talk pages_, but "Photographe russe" contains the actual _articles_. Therefore there is no overlap between the two.

There is currently no way to mix category trees from articles and talk pages, but I'll leave this open as a feature request.

You can exclude specific _templates_ on talk pages, maybe that can help you right now.

**Comment by magnusmanske** [comment]
Here is the query _I think_ you want. Runs a few minutes though.

https://petscan.wmflabs.org/?psid=16228811

**Comment by cjerabek** [comment]
Hello Magnus,

Thank you very much. It sounds very logical, which apparently I am not !

Best regards,
Cyrille JERABEK
06 72 76 59 27


Le mar. 12 mai 2020 à 17:47, Magnus Manske <notifications@github.com> a
écrit :

**Comment by cjerabek** [comment]
Thank you VERY MUCH.
This is of great help and will allow me to find interesting blind spots and
correct them !
(I already made a series of changes ton the articles)

Bien cordialement,
Cyrille JERABEK
06 72 76 59 27


Le mar. 12 mai 2020 à 18:00, Magnus Manske <notifications@github.com> a
écrit :
