### ISSUE TITLE
sort parameter not being honoured?

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/petscan_rs#6]
have an issue with http://petscan.wmflabs.org/?psid=10683037 which is being asked to sort by title, but delivers results in QId order. 

<img width="915" alt="Screenshot 2019-08-22 at 15 25 40" src="https://user-images.githubusercontent.com/9000789/63522948-28ab7b00-c4f1-11e9-82b0-e9f1c497bd2f.png">

**Comment by magnusmanske** [comment]
Fixed ([fast example](http://petscan.wmflabs.org/?psid=10683775))
