### ISSUE TITLE
Petscan has been down

### ISSUE THREAD

**Issue by mgoose109** [magnusmanske/petscan_rs#61]
Seems like it has been down non-stop since the previous issues were closed. I only need to use it for one project, but during the past two weeks I've only been able to use it twice after many attempts.  Please help, Magnus. I think I read a post somewhere in which you said you wouldn't be able to host Petscan anymore due to too many requests being made to the server? Is that the reason for these problems?

**Comment by magnusmanske** [comment]
Recent improvements and an auto-restarter should have made it more stable. Is this still not working for you?

**Comment by mgoose109** [comment]
Thanks for replying. It turns out at some point I bookmarked the link to the site and somehow saved it with a typo ("wfmlabs" instead of wmflabs"). The site is up but on sending a request, Nginx returns a bad gateway error.

**Comment by trittich** [comment]
I also get a "502 Bad Gateway" when trying to use the tool.

If this problem persists - Is there any alternative way to get a list of all subcategories (and their subcategories and so on) of a single category?
Since my query will probably result in a list with way more than 500 categories, I guess that the api is no option since its limited to 500 entries, right?

**Comment by mgoose109** [comment]
I can answer the second part. No, the api isn't limited to 500 entries, the two times I've managed to get a result, I got csv files with some 6000 and 8000 subcategory entries (maximum depth).

**Comment by magnusmanske** [comment]
PetScan still goes 502 apparently, but should work most of the time. I am working on a watcher script that will restart PetScan when it goes 502.
The MediaWiki API can be used to get the category trees, of any size, but it is gruesome manual work unless you can script it.

**Comment by trittich** [comment]
Ok it works for me again, thank you!

**Comment by mgoose109** [comment]
Nice! That will be helpful. Petscan works great now, thanks!
