### ISSUE TITLE
Thumbnails view of files not working

### ISSUE THREAD

**Issue by wargo32** [magnusmanske/petscan_rs#62]
When I view files (in namespace File) and in the upper-right corner of results list under the form I click "Thumbnails" it does not show thumbnails. Probably because it loads HTML of File: pages instead of images itself.

**Comment by MarcLacoste** [comment]
same here, eg https://petscan.wmflabs.org/?psid=16464958
![image](https://user-images.githubusercontent.com/66764895/84345294-4a274180-abad-11ea-9563-591437750531.png)

**Comment by MarcLacoste** [comment]
![Screenshot_2020-06-26-09-48-57-755_com android chrome](https://user-images.githubusercontent.com/66764895/85833681-68d32e00-b792-11ea-9a0d-59bbadca619a.jpg)
Previous screenshot was on chrome on a Chromebook. Same in Android

**Comment by JotaCartas** [comment]
the same append  to me

**Comment by MarcLacoste** [comment]
problem still active

**Comment by MarcLacoste** [comment]
Still not working

**Comment by MarcLacoste** [comment]
still broken
