### ISSUE TITLE
Using Petscan through Python

### ISSUE THREAD

**Issue by carlinmack** [magnusmanske/petscan_rs#64]
Hi,

I'm working on [a tool](https://github.com/carlinmack/NamespaceDatabase) to create a database of Wikipedia edits, and I'd like to make a blocked user feature available. I've managed to do this manually by using PetScan to get the Blocked_Wikipedia_users category. However I want to script this, but when I try to do something like this:

```python 
url = <auto-run-petscan-url>
urllib.request.urlretrieve(url, "./Blocked_Wikipedia_users.csv")
```

I get 502 errors. Is there a better way to be doing this?

**Comment by magnusmanske** [comment]
Odd. This works for me (not the full category tree but in principle):
```
curl 'https://petscan.wmflabs.org/?psid=18577505&format=csv'
```
Build your query then replace the psid, that URL should work. If not, maybe some Python issue?

**Comment by afarlie** [comment]
I will note here that Pywikibot has a PetScanPageGenerator (see https://doc.wikimedia.org/pywikibot/master/api_ref/pywikibot.html#module-pywikibot.pagegenerators). My understanding is that you supply the paramaters in the extra_options, as "key", "value" pairs, where the "key" 's are the names of the form elements in Petscan.  You may wish to ask some pywikibot coders about this.
