### ISSUE TITLE
Adding a 'map' output format

### ISSUE THREAD

**Issue by Thierry-Caro** [magnusmanske/petscan_rs#67]
I think it would be great if we could have another option in the 'Format' section of 'Output'. 'Map' would automatically filter the results with items that have a Wikidata item and a P625 statement. It would then display a map of what remains. That way, we could create maps very easily while still crossing categories, templates and the likes with one another.

**Comment by magnusmanske** [comment]
Nice idea! What format should that be? SVG?

**Comment by magnusmanske** [comment]
Or KML for overlay info?

**Comment by Thierry-Caro** [comment]
Hello! I would go for KML. This is what I had in mind.

**Comment by magnusmanske** [comment]
Done now.

Example:
https://petscan.wmflabs.org/?psid=18591379&format=kml

Made a viewer (uses above URL but need to escape the &):
https://wikidata-todo.toolforge.org/render_kml.html?kml=https://petscan.wmflabs.org/?psid=18591379%26format=kml

**Comment by Thierry-Caro** [comment]
Thank you very much. The result is very neat.
