### ISSUE TITLE
Unable to search the Cantonese Wikipedia (zh_yuewiki)

### ISSUE THREAD

**Issue by szc126** [magnusmanske/petscan_rs#68]
Does PetScan support the Cantonese Wikipedia (zh-yue.wikipedia.org)? I have tried zh-yue, zh_yue, zhyue, and yue as the language; neither one seems to work.

**Comment by magnusmanske** [comment]
This is fixed now. Use `zh-yue` or `zh-classical`, respectively, with `wikipedia` as project.
