### ISSUE TITLE
Generate thumbnails in Wiki output doesn't work

### ISSUE THREAD

**Issue by MB-one** [magnusmanske/petscan_rs#69]
thumbnails are not shown

**Comment by JotaCartas** [comment]
The same for me, since may 31, 2020

**Comment by MarcLacoste** [comment]
See https://github.com/magnusmanske/petscan_rs/issues/62
still not working today

**Comment by magnusmanske** [comment]
Fixed now.

By default, you will get [linked files](https://petscan.wmflabs.org/?psid=16464958&format=wiki).
If you want [thumbnails](https://petscan.wmflabs.org/?psid=18604533&format=wiki), check the "Generate thumbnails in Wiki output".
