### ISSUE TITLE
Links to Wikipedia truncated at apostrophe

### ISSUE THREAD

**Issue by omhalck** [magnusmanske/petscan_rs#7]
Hello --

It appears that the links from PetScan results to Wikipedia are truncated when an apostrophe is encountered. For example, in the query with PSID=10699350, the second result is for the song "You've Got a Friend", and links to the following page:
https://en.wikipedia.org/wiki/You

The old version of PetScan gives the correct link:
https://en.wikipedia.org/wiki/You%27ve_Got_a_Friend

**Comment by magnusmanske** [comment]
Fixed
