### ISSUE TITLE
Add plaintext output option

### ISSUE THREAD

**Issue by Ian-07** [magnusmanske/petscan_rs#73]
As suggested [here](https://en.wikipedia.org/wiki/Wikipedia_talk:AutoWikiBrowser#Importing_PetScan_query_list_to_AWB?), it would be nice to have an option to output PetScan results as a raw list, which would make it easier to import into AWB (just copy-paste it into the list box) or perhaps into one's [watchlist](https://en.wikipedia.org/wiki/Special:EditWatchlist/raw).

**Comment by Ian-07** [comment]
Just learned this can already be done with the plain text option in PagePile: https://pagepile.toolforge.org/api.php?action=get_data&id=31670

However, it might be nice to make this more accessible.

**Comment by magnusmanske** [comment]
Now live
