### ISSUE TITLE
error message "The supplied language code was not recognized" when creating objects for Commons-Categories

### ISSUE THREAD

**Issue by M2k-dewiki** [magnusmanske/petscan_rs#76]
Hello,

when I try to to create Wikidata objects for unconnected Commons-Categories using Petscan/Quickstatements, for example using this URL:

https://petscan.wmflabs.org/?min_sitelink_count=&negcats=Wikipedia:L%C3%B6schkandidat%0AWikipedia:Schnelll%C3%B6schen&ns%5B14%5D=1&edits%5Bbots%5D=both&cb_labels_any_l=1&show_redirects=no&ns%5B0%5D=1&ns%5B4%5D=1&language=commons&categories=Streets_in_Doberlug-Kirchhain&wikidata_item=without&search_max_results=500&edits%5Bflagged%5D=both&cb_labels_yes_l=1&cb_labels_no_l=1&project=wikimedia&combination=union&interface_language=en&edits%5Banons%5D=both&search_wiki=&doit=&al_commands=P31%3AQ79007%0AP17%3AQ183%0AP131%3AQ371098

(and testing with one entry checked) I get the error message "The supplied language code was not recognized".

Creating Wikidata-Objects for unconnected Commons-Category using Petscan already worked in the past, but I think this might have been with an older version of PetScan.

Thanks a lot!

Kind regards,
M2k~dewiki

https://www.wikidata.org/wiki/Help_talk:QuickStatements#Adding_Link_to_Wikimedia_Commons

https://bitbucket.org/magnusmanske/petscan/issues/168/error-message-the-supplied-language-code

**Comment by magnusmanske** [comment]
This should work now
