### ISSUE TITLE
Re-enable CORS

### ISSUE THREAD

**Issue by simon04** [magnusmanske/petscan_rs#79]
Fetching images for a Commons category is broken on https://locator-tool.toolforge.org/ due to PetScan no longer sending CORS headers. Please re-enable [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)!

**Comment by magnusmanske** [comment]
This should be done now, please re-open if not.

**Comment by simon04** [comment]
https://github.com/magnusmanske/petscan_rs/commit/e61ed066c8c71f4b73d1e7c8dc43b55918495cea#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR213
