### ISSUE TITLE
'manual wiki requested as output, but not set' issue

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/petscan_rs#8]
https://petscan1.wmflabs.org/?psid=9021965
versus
http://petscan.wmflabs.org/?psid=9021965

... former gets 146 results, latter gets 'manual wiki requested as output, but not set'

**Comment by magnusmanske** [comment]
Using the "manual list" wiki as output wiki is a deprecated hack. One should use the new bespoke wiki option under "Other sources/Use wiki". I have put in place a rewrite hack to maintain compatibility with existing PSIDs.
