### ISSUE TITLE
Server(ServerError { code: 1290 ...

### ISSUE THREAD

**Issue by suciokhan** [magnusmanske/petscan_rs#82]
I received an error when trying to retrieve titles within 2-hops of "Mathematics" or "Fields of mathematics". 

This is the full error message:

Server(ServerError { code: 1290, message: "The MariaDB server is running with the --read-only option so it cannot execute this statement", state: "HY000" })

I've tried with HTML and TSV returns, and it doesn't seem to effect the error message.

**Comment by VojtechDostal** [comment]
I am getting the same error when running a different type of job.

**Comment by Lofhi** [comment]
ToolsDB is under maintenance, because it "suffered a breakage in replication". The Wikimedia Cloud Services team did not give the estimated date of return to normal. They hope that with the "read-only mode [...] the backup will not take terribly long".

**Comment by WilliamAvery** [comment]
There is a Phabricator issue https://phabricator.wikimedia.org/T267682

**Comment by WilliamAvery** [comment]
The Phabricator task to fix this is https://phabricator.wikimedia.org/T266587

**Comment by magnusmanske** [comment]
upstream, wontfix
