### ISSUE TITLE
Feature request: sorting titles by DEFAULTSORT

### ISSUE THREAD

**Issue by DP-jawiki** [magnusmanske/petscan_rs#83]
Hi,

My suggestion: would it be possible to add an option of sorting titles by sort key?

For pages titled with Kanji, or Chinese characters, PetScan cannot sort titles into the Gojūon order by Kana characters, which is commonly used to set sort keys on Japanese Wikipedia, but sort into the Unicode order when setting "Sort" to "by title". The similar problem could be seen in other East Asian languages written with CJK ideographs.

Looking forward to see this problem would be solved in the future enhancements. Best regards ;-)

**Comment by magnusmanske** [comment]
now live
