### ISSUE TITLE
be-tarask.wiki is not working with Wikidata

### ISSUE THREAD

**Issue by rwduck** [magnusmanske/petscan_rs#85]
If you create query for be-tarask lang and wikipedia project it works okay, but when you select anything on Wikidata tab, it returns 0 results regardless of your choice.

Query example: https://petscan.wmflabs.org/?psid=18033285
Same query with Wikidata: https://petscan.wmflabs.org/?psid=18033291

**Comment by magnusmanske** [comment]
This should be fixed now. The "query example" returns the same order-of-magnitude entries as the "Wikidata query", instead of 0.
