### ISSUE TITLE
Unable to set enwikiquote as manual wiki

### ISSUE THREAD

**Issue by generalist** [magnusmanske/petscan_rs#9]
(This was prompted by the same set of queries as #8 but it's a separate issue, I think)

The textbox on "other sources > use wiki" allows you to specify various different wikis, but doesn't recognise Wikiquote.

For example, to find all people in "Category:Presidents of the United States" on enwiki and with a commons link is https://petscan.wmflabs.org/?psid=10701283 ; or with an enwikisource link, https://petscan.wmflabs.org/?psid=10701286

However, setting this to be "enwikiquote" has the box highlighted as invalid, and greys out the "do it" button. The same problem for frwikiquote, dewikiquote, etc.

**Comment by magnusmanske** [comment]
Resolved, use `enwikiquote`, [example](http://petscan.wmflabs.org/?psid=10782025).
