### ISSUE TITLE
Petscan UI, should warn about "blank" search term in Other Sources...

### ISSUE THREAD

**Issue by afarlie** [magnusmanske/petscan_rs#94]
I was testing the new search filter you had implemented.
https://petscan.wmflabs.org/?psid=18645280 this returned 0 results.
(Given the potential size of the query, I wasn't surprised.)

I then made the following query which should have returned 88 results (the size of the category on Commons) : https://petscan.wmflabs.org/?psid=18645368 which also returned 0 results.

What seems to be the cause of the non return of any results is that I had failed to clear the additional boxes for a 'search' in other sources (when creating the queries),  which causes a 'blank' search to run, this naturally would fail to produce any results for a given query. 

My suggestion would be that the UI warns about a blank search term, if the additional boxes relating to it are set in the 'Other Sources' tab. 

Alternatively the error reported by the UI  could make a distinction between 'blank' searches (which are typically not a user intention) , and searches that ran and genuinely produced no results,

**Comment by magnusmanske** [comment]
Fixed the back-end so that so search is performed if wither the query or wiki parameter are blank.
Example: https://petscan.wmflabs.org/?psid=18655336
