### ISSUE TITLE
possibility for filtering deprecated statements n Wikidata

### ISSUE THREAD

**Issue by JAnDud** [magnusmanske/petscan_rs#97]
https://petscan.wmflabs.org/?psid=1313317

Here is query for people with authority data od WD but no authority template on WP.

But there are also people who have e.g. VIAF, but this statement is deprecated 
https://www.wikidata.org/wiki/Q956657

There is no easy possibility to filter out these items

**Comment by magnusmanske** [comment]
"Uses items/props" can not get information about ranks (eg deprecated) in Wikidata, as it is using the pagelinks table which was never designed for this kind of request.

You can try to use SPARQL where you can filter on preferred/normal/deprecated but the query engine might timeout, depending on the query.
