### ISSUE TITLE
Adding lingualibre

### ISSUE THREAD

**Issue by belett** [magnusmanske/petscan_rs#99]
Hi,

Maybe a dumb question but would it be possible to add https://lingualibre.org to PetScan?

It's not a wikimedia project but it's closely integrated and I think it could be useful.

**Comment by magnusmanske** [comment]
Much of PetScan depends on access to the database replicas. Unless that data is replicated in the Toolforge replicas, I don't think it's possible, or even worth it, given how much of the functionality would not work.

If the lingualibre DBs are indeed replicate, please reopen this ticket and let me know!

**Comment by Poslovitch** [comment]
Hi @magnusmanske !
LinguaLibre DBs can't be part of the Wiki Replicas since LinguaLibre's not a WMF-backed project.
But would a "clone" of the DBs provided as a [ToolsDB](https://wikitech.wikimedia.org/wiki/Help:Toolforge/Database#User_databases) with public read-access do the job ?

**Comment by hugolpz** [comment]
@Poslovitch : Technically, LL have been funded by both Wikimedia France (2016: 10k€, 2020: 40k€) and WMF (2017-2018: 30k$).
Wikimedia France is the first reference point, but both are key contributors to the project.
